# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai.v1 import worker_pb2 as ai_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/bilinotify.ai.v1.AIWorker/GetCapabilities',
                request_serializer=ai_dot_v1_dot_worker__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_worker__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.TestProvider = channel.unary_unary(
                '/bilinotify.ai.v1.AIWorker/TestProvider',
                request_serializer=ai_dot_v1_dot_worker__pb2.TestProviderRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_worker__pb2.TestProviderResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_stream(
                '/bilinotify.ai.v1.AIWorker/Transcribe',
                request_serializer=ai_dot_v1_dot_worker__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
                _registered_method=True)
        self.Summarize = channel.unary_stream(
                '/bilinotify.ai.v1.AIWorker/Summarize',
                request_serializer=ai_dot_v1_dot_worker__pb2.SummaryRequest.SerializeToString,
                response_deserializer=ai_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
                _registered_method=True)


class AIWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestProvider(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=ai_dot_v1_dot_worker__pb2.CapabilitiesRequest.FromString,
                    response_serializer=ai_dot_v1_dot_worker__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'TestProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.TestProvider,
                    request_deserializer=ai_dot_v1_dot_worker__pb2.TestProviderRequest.FromString,
                    response_serializer=ai_dot_v1_dot_worker__pb2.TestProviderResponse.SerializeToString,
            ),
            'Transcribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=ai_dot_v1_dot_worker__pb2.TranscribeRequest.FromString,
                    response_serializer=ai_dot_v1_dot_worker__pb2.WorkerEvent.SerializeToString,
            ),
            'Summarize': grpc.unary_stream_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=ai_dot_v1_dot_worker__pb2.SummaryRequest.FromString,
                    response_serializer=ai_dot_v1_dot_worker__pb2.WorkerEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bilinotify.ai.v1.AIWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bilinotify.ai.v1.AIWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilinotify.ai.v1.AIWorker/GetCapabilities',
            ai_dot_v1_dot_worker__pb2.CapabilitiesRequest.SerializeToString,
            ai_dot_v1_dot_worker__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bilinotify.ai.v1.AIWorker/TestProvider',
            ai_dot_v1_dot_worker__pb2.TestProviderRequest.SerializeToString,
            ai_dot_v1_dot_worker__pb2.TestProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bilinotify.ai.v1.AIWorker/Transcribe',
            ai_dot_v1_dot_worker__pb2.TranscribeRequest.SerializeToString,
            ai_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bilinotify.ai.v1.AIWorker/Summarize',
            ai_dot_v1_dot_worker__pb2.SummaryRequest.SerializeToString,
            ai_dot_v1_dot_worker__pb2.WorkerEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
