// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: ai/v1/worker.proto

package aiworkerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIWorker_GetCapabilities_FullMethodName = "/bilinotify.ai.v1.AIWorker/GetCapabilities"
	AIWorker_Transcribe_FullMethodName      = "/bilinotify.ai.v1.AIWorker/Transcribe"
	AIWorker_Summarize_FullMethodName       = "/bilinotify.ai.v1.AIWorker/Summarize"
)

// AIWorkerClient is the client API for AIWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIWorkerClient interface {
	GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerEvent], error)
	Summarize(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerEvent], error)
}

type aIWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewAIWorkerClient(cc grpc.ClientConnInterface) AIWorkerClient {
	return &aIWorkerClient{cc}
}

func (c *aIWorkerClient) GetCapabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, AIWorker_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIWorkerClient) Transcribe(ctx context.Context, in *TranscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIWorker_ServiceDesc.Streams[0], AIWorker_Transcribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TranscribeRequest, WorkerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_TranscribeClient = grpc.ServerStreamingClient[WorkerEvent]

func (c *aIWorkerClient) Summarize(ctx context.Context, in *SummaryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIWorker_ServiceDesc.Streams[1], AIWorker_Summarize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SummaryRequest, WorkerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_SummarizeClient = grpc.ServerStreamingClient[WorkerEvent]

// AIWorkerServer is the server API for AIWorker service.
// All implementations must embed UnimplementedAIWorkerServer
// for forward compatibility.
type AIWorkerServer interface {
	GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	Transcribe(*TranscribeRequest, grpc.ServerStreamingServer[WorkerEvent]) error
	Summarize(*SummaryRequest, grpc.ServerStreamingServer[WorkerEvent]) error
	mustEmbedUnimplementedAIWorkerServer()
}

// UnimplementedAIWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIWorkerServer struct{}

func (UnimplementedAIWorkerServer) GetCapabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedAIWorkerServer) Transcribe(*TranscribeRequest, grpc.ServerStreamingServer[WorkerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedAIWorkerServer) Summarize(*SummaryRequest, grpc.ServerStreamingServer[WorkerEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Summarize not implemented")
}
func (UnimplementedAIWorkerServer) mustEmbedUnimplementedAIWorkerServer() {}
func (UnimplementedAIWorkerServer) testEmbeddedByValue()                  {}

// UnsafeAIWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIWorkerServer will
// result in compilation errors.
type UnsafeAIWorkerServer interface {
	mustEmbedUnimplementedAIWorkerServer()
}

func RegisterAIWorkerServer(s grpc.ServiceRegistrar, srv AIWorkerServer) {
	// If the following call pancis, it indicates UnimplementedAIWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIWorker_ServiceDesc, srv)
}

func _AIWorker_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIWorkerServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIWorker_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIWorkerServer).GetCapabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIWorker_Transcribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TranscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIWorkerServer).Transcribe(m, &grpc.GenericServerStream[TranscribeRequest, WorkerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_TranscribeServer = grpc.ServerStreamingServer[WorkerEvent]

func _AIWorker_Summarize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SummaryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIWorkerServer).Summarize(m, &grpc.GenericServerStream[SummaryRequest, WorkerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIWorker_SummarizeServer = grpc.ServerStreamingServer[WorkerEvent]

// AIWorker_ServiceDesc is the grpc.ServiceDesc for AIWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bilinotify.ai.v1.AIWorker",
	HandlerType: (*AIWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _AIWorker_GetCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcribe",
			Handler:       _AIWorker_Transcribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Summarize",
			Handler:       _AIWorker_Summarize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai/v1/worker.proto",
}
