// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: ai/v1/worker.proto

package aiworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_ai_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Version              string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	YtDlpAvailable       bool                   `protobuf:"varint,2,opt,name=yt_dlp_available,json=ytDlpAvailable,proto3" json:"yt_dlp_available,omitempty"`
	FfmpegAvailable      bool                   `protobuf:"varint,3,opt,name=ffmpeg_available,json=ffmpegAvailable,proto3" json:"ffmpeg_available,omitempty"`
	ActiveTranscriptions int32                  `protobuf:"varint,4,opt,name=active_transcriptions,json=activeTranscriptions,proto3" json:"active_transcriptions,omitempty"`
	ActiveSummaries      int32                  `protobuf:"varint,5,opt,name=active_summaries,json=activeSummaries,proto3" json:"active_summaries,omitempty"`
	CacheBytes           int64                  `protobuf:"varint,6,opt,name=cache_bytes,json=cacheBytes,proto3" json:"cache_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_ai_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CapabilitiesResponse) GetYtDlpAvailable() bool {
	if x != nil {
		return x.YtDlpAvailable
	}
	return false
}

func (x *CapabilitiesResponse) GetFfmpegAvailable() bool {
	if x != nil {
		return x.FfmpegAvailable
	}
	return false
}

func (x *CapabilitiesResponse) GetActiveTranscriptions() int32 {
	if x != nil {
		return x.ActiveTranscriptions
	}
	return 0
}

func (x *CapabilitiesResponse) GetActiveSummaries() int32 {
	if x != nil {
		return x.ActiveSummaries
	}
	return 0
}

func (x *CapabilitiesResponse) GetCacheBytes() int64 {
	if x != nil {
		return x.CacheBytes
	}
	return 0
}

type ProviderConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl            string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey             string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Model              string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Language           string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Prompt             string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Temperature        float64                `protobuf:"fixed64,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxOutputTokens    int64                  `protobuf:"varint,7,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	ContextWindowChars int32                  `protobuf:"varint,8,opt,name=context_window_chars,json=contextWindowChars,proto3" json:"context_window_chars,omitempty"`
	TimeoutSec         int32                  `protobuf:"varint,9,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_ai_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ProviderConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ProviderConfig) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ProviderConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ProviderConfig) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *ProviderConfig) GetContextWindowChars() int32 {
	if x != nil {
		return x.ContextWindowChars
	}
	return 0
}

func (x *ProviderConfig) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type TestProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Provider      *ProviderConfig        `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderRequest) Reset() {
	*x = TestProviderRequest{}
	mi := &file_ai_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderRequest) ProtoMessage() {}

func (x *TestProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderRequest.ProtoReflect.Descriptor instead.
func (*TestProviderRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TestProviderRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TestProviderRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

type TestProviderResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ok                 bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	LatencyMs          int64                  `protobuf:"varint,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ProviderHttpStatus int32                  `protobuf:"varint,5,opt,name=provider_http_status,json=providerHttpStatus,proto3" json:"provider_http_status,omitempty"`
	ProviderError      string                 `protobuf:"bytes,6,opt,name=provider_error,json=providerError,proto3" json:"provider_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TestProviderResponse) Reset() {
	*x = TestProviderResponse{}
	mi := &file_ai_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderResponse) ProtoMessage() {}

func (x *TestProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderResponse.ProtoReflect.Descriptor instead.
func (*TestProviderResponse) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *TestProviderResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TestProviderResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TestProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestProviderResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TestProviderResponse) GetProviderHttpStatus() int32 {
	if x != nil {
		return x.ProviderHttpStatus
	}
	return 0
}

func (x *TestProviderResponse) GetProviderError() string {
	if x != nil {
		return x.ProviderError
	}
	return ""
}

type TranscribeRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Bvid               string                 `protobuf:"bytes,2,opt,name=bvid,proto3" json:"bvid,omitempty"`
	Page               int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Cookies            map[string]string      `protobuf:"bytes,4,rep,name=cookies,proto3" json:"cookies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Provider           *ProviderConfig        `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	FailureCacheTtlSec int64                  `protobuf:"varint,6,opt,name=failure_cache_ttl_sec,json=failureCacheTtlSec,proto3" json:"failure_cache_ttl_sec,omitempty"`
	CacheMaxBytes      int64                  `protobuf:"varint,7,opt,name=cache_max_bytes,json=cacheMaxBytes,proto3" json:"cache_max_bytes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_ai_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *TranscribeRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TranscribeRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

func (x *TranscribeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TranscribeRequest) GetCookies() map[string]string {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *TranscribeRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *TranscribeRequest) GetFailureCacheTtlSec() int64 {
	if x != nil {
		return x.FailureCacheTtlSec
	}
	return 0
}

func (x *TranscribeRequest) GetCacheMaxBytes() int64 {
	if x != nil {
		return x.CacheMaxBytes
	}
	return 0
}

type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Provider      *ProviderConfig        `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	ChunkPrompt   string                 `protobuf:"bytes,5,opt,name=chunk_prompt,json=chunkPrompt,proto3" json:"chunk_prompt,omitempty"`
	ReducePrompt  string                 `protobuf:"bytes,6,opt,name=reduce_prompt,json=reducePrompt,proto3" json:"reduce_prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_ai_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *SummaryRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SummaryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SummaryRequest) GetProvider() *ProviderConfig {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *SummaryRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *SummaryRequest) GetChunkPrompt() string {
	if x != nil {
		return x.ChunkPrompt
	}
	return ""
}

func (x *SummaryRequest) GetReducePrompt() string {
	if x != nil {
		return x.ReducePrompt
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Percent       int32                  `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_ai_v1_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{7}
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetPercent() int32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TranscriptSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartMs       int64                  `protobuf:"varint,1,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int64                  `protobuf:"varint,2,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptSegment) Reset() {
	*x = TranscriptSegment{}
	mi := &file_ai_v1_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptSegment) ProtoMessage() {}

func (x *TranscriptSegment) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptSegment.ProtoReflect.Descriptor instead.
func (*TranscriptSegment) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{8}
}

func (x *TranscriptSegment) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *TranscriptSegment) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *TranscriptSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TranscriptPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Segments      []*TranscriptSegment   `protobuf:"bytes,5,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptPage) Reset() {
	*x = TranscriptPage{}
	mi := &file_ai_v1_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptPage) ProtoMessage() {}

func (x *TranscriptPage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptPage.ProtoReflect.Descriptor instead.
func (*TranscriptPage) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{9}
}

func (x *TranscriptPage) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TranscriptPage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *TranscriptPage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TranscriptPage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TranscriptPage) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type TranscriptionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Pages         []*TranscriptPage      `protobuf:"bytes,3,rep,name=pages,proto3" json:"pages,omitempty"`
	Usage         *structpb.Struct       `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionResult) Reset() {
	*x = TranscriptionResult{}
	mi := &file_ai_v1_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionResult) ProtoMessage() {}

func (x *TranscriptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionResult.ProtoReflect.Descriptor instead.
func (*TranscriptionResult) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{10}
}

func (x *TranscriptionResult) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

func (x *TranscriptionResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TranscriptionResult) GetPages() []*TranscriptPage {
	if x != nil {
		return x.Pages
	}
	return nil
}

func (x *TranscriptionResult) GetUsage() *structpb.Struct {
	if x != nil {
		return x.Usage
	}
	return nil
}

type SummaryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markdown      string                 `protobuf:"bytes,1,opt,name=markdown,proto3" json:"markdown,omitempty"`
	Usage         *structpb.Struct       `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResult) Reset() {
	*x = SummaryResult{}
	mi := &file_ai_v1_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResult) ProtoMessage() {}

func (x *SummaryResult) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResult.ProtoReflect.Descriptor instead.
func (*SummaryResult) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{11}
}

func (x *SummaryResult) GetMarkdown() string {
	if x != nil {
		return x.Markdown
	}
	return ""
}

func (x *SummaryResult) GetUsage() *structpb.Struct {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_ai_v1_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{12}
}

func (x *Warning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*WorkerEvent_Progress
	//	*WorkerEvent_Transcription
	//	*WorkerEvent_Summary
	//	*WorkerEvent_Warning
	Event         isWorkerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerEvent) Reset() {
	*x = WorkerEvent{}
	mi := &file_ai_v1_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerEvent) ProtoMessage() {}

func (x *WorkerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_v1_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerEvent.ProtoReflect.Descriptor instead.
func (*WorkerEvent) Descriptor() ([]byte, []int) {
	return file_ai_v1_worker_proto_rawDescGZIP(), []int{13}
}

func (x *WorkerEvent) GetEvent() isWorkerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WorkerEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *WorkerEvent) GetTranscription() *TranscriptionResult {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Transcription); ok {
			return x.Transcription
		}
	}
	return nil
}

func (x *WorkerEvent) GetSummary() *SummaryResult {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Summary); ok {
			return x.Summary
		}
	}
	return nil
}

func (x *WorkerEvent) GetWarning() *Warning {
	if x != nil {
		if x, ok := x.Event.(*WorkerEvent_Warning); ok {
			return x.Warning
		}
	}
	return nil
}

type isWorkerEvent_Event interface {
	isWorkerEvent_Event()
}

type WorkerEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type WorkerEvent_Transcription struct {
	Transcription *TranscriptionResult `protobuf:"bytes,2,opt,name=transcription,proto3,oneof"`
}

type WorkerEvent_Summary struct {
	Summary *SummaryResult `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

type WorkerEvent_Warning struct {
	Warning *Warning `protobuf:"bytes,4,opt,name=warning,proto3,oneof"`
}

func (*WorkerEvent_Progress) isWorkerEvent_Event() {}

func (*WorkerEvent_Transcription) isWorkerEvent_Event() {}

func (*WorkerEvent_Summary) isWorkerEvent_Event() {}

func (*WorkerEvent_Warning) isWorkerEvent_Event() {}

var File_ai_v1_worker_proto protoreflect.FileDescriptor

const file_ai_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x12ai/v1/worker.proto\x12\x10bilinotify.ai.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x15\n" +
	"\x13CapabilitiesRequest\"\x86\x02\n" +
	"\x14CapabilitiesResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12(\n" +
	"\x10yt_dlp_available\x18\x02 \x01(\bR\x0eytDlpAvailable\x12)\n" +
	"\x10ffmpeg_available\x18\x03 \x01(\bR\x0fffmpegAvailable\x123\n" +
	"\x15active_transcriptions\x18\x04 \x01(\x05R\x14activeTranscriptions\x12)\n" +
	"\x10active_summaries\x18\x05 \x01(\x05R\x0factiveSummaries\x12\x1f\n" +
	"\vcache_bytes\x18\x06 \x01(\x03R\n" +
	"cacheBytes\"\xaf\x02\n" +
	"\x0eProviderConfig\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x01R\vtemperature\x12*\n" +
	"\x11max_output_tokens\x18\a \x01(\x03R\x0fmaxOutputTokens\x120\n" +
	"\x14context_window_chars\x18\b \x01(\x05R\x12contextWindowChars\x12\x1f\n" +
	"\vtimeout_sec\x18\t \x01(\x05R\n" +
	"timeoutSec\"g\n" +
	"\x13TestProviderRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12<\n" +
	"\bprovider\x18\x02 \x01(\v2 .bilinotify.ai.v1.ProviderConfigR\bprovider\"\xd7\x01\n" +
	"\x14TestProviderResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x120\n" +
	"\x14provider_http_status\x18\x05 \x01(\x05R\x12providerHttpStatus\x12%\n" +
	"\x0eprovider_error\x18\x06 \x01(\tR\rproviderError\"\xf3\x02\n" +
	"\x11TranscribeRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04bvid\x18\x02 \x01(\tR\x04bvid\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12J\n" +
	"\acookies\x18\x04 \x03(\v20.bilinotify.ai.v1.TranscribeRequest.CookiesEntryR\acookies\x12<\n" +
	"\bprovider\x18\x05 \x01(\v2 .bilinotify.ai.v1.ProviderConfigR\bprovider\x121\n" +
	"\x15failure_cache_ttl_sec\x18\x06 \x01(\x03R\x12failureCacheTtlSec\x12&\n" +
	"\x0fcache_max_bytes\x18\a \x01(\x03R\rcacheMaxBytes\x1a:\n" +
	"\fCookiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x0eSummaryRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12<\n" +
	"\bprovider\x18\x03 \x01(\v2 .bilinotify.ai.v1.ProviderConfigR\bprovider\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12!\n" +
	"\fchunk_prompt\x18\x05 \x01(\tR\vchunkPrompt\x12#\n" +
	"\rreduce_prompt\x18\x06 \x01(\tR\freducePrompt\"T\n" +
	"\bProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x05R\apercent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"Y\n" +
	"\x11TranscriptSegment\x12\x19\n" +
	"\bstart_ms\x18\x01 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x02 \x01(\x03R\x05endMs\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xae\x01\n" +
	"\x0eTranscriptPage\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12?\n" +
	"\bsegments\x18\x05 \x03(\v2#.bilinotify.ai.v1.TranscriptSegmentR\bsegments\"\xa6\x01\n" +
	"\x13TranscriptionResult\x12\x12\n" +
	"\x04bvid\x18\x01 \x01(\tR\x04bvid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x126\n" +
	"\x05pages\x18\x03 \x03(\v2 .bilinotify.ai.v1.TranscriptPageR\x05pages\x12-\n" +
	"\x05usage\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05usage\"Z\n" +
	"\rSummaryResult\x12\x1a\n" +
	"\bmarkdown\x18\x01 \x01(\tR\bmarkdown\x12-\n" +
	"\x05usage\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05usage\"7\n" +
	"\aWarning\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x93\x02\n" +
	"\vWorkerEvent\x128\n" +
	"\bprogress\x18\x01 \x01(\v2\x1a.bilinotify.ai.v1.ProgressH\x00R\bprogress\x12M\n" +
	"\rtranscription\x18\x02 \x01(\v2%.bilinotify.ai.v1.TranscriptionResultH\x00R\rtranscription\x12;\n" +
	"\asummary\x18\x03 \x01(\v2\x1f.bilinotify.ai.v1.SummaryResultH\x00R\asummary\x125\n" +
	"\awarning\x18\x04 \x01(\v2\x19.bilinotify.ai.v1.WarningH\x00R\awarningB\a\n" +
	"\x05event2\xef\x02\n" +
	"\bAIWorker\x12`\n" +
	"\x0fGetCapabilities\x12%.bilinotify.ai.v1.CapabilitiesRequest\x1a&.bilinotify.ai.v1.CapabilitiesResponse\x12]\n" +
	"\fTestProvider\x12%.bilinotify.ai.v1.TestProviderRequest\x1a&.bilinotify.ai.v1.TestProviderResponse\x12R\n" +
	"\n" +
	"Transcribe\x12#.bilinotify.ai.v1.TranscribeRequest\x1a\x1d.bilinotify.ai.v1.WorkerEvent0\x01\x12N\n" +
	"\tSummarize\x12 .bilinotify.ai.v1.SummaryRequest\x1a\x1d.bilinotify.ai.v1.WorkerEvent0\x01BBZ@github.com/linxin2429/bili_notify/internal/aiworkerpb;aiworkerpbb\x06proto3"

var (
	file_ai_v1_worker_proto_rawDescOnce sync.Once
	file_ai_v1_worker_proto_rawDescData []byte
)

func file_ai_v1_worker_proto_rawDescGZIP() []byte {
	file_ai_v1_worker_proto_rawDescOnce.Do(func() {
		file_ai_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_v1_worker_proto_rawDesc), len(file_ai_v1_worker_proto_rawDesc)))
	})
	return file_ai_v1_worker_proto_rawDescData
}

var file_ai_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_ai_v1_worker_proto_goTypes = []any{
	(*CapabilitiesRequest)(nil),  // 0: bilinotify.ai.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil), // 1: bilinotify.ai.v1.CapabilitiesResponse
	(*ProviderConfig)(nil),       // 2: bilinotify.ai.v1.ProviderConfig
	(*TestProviderRequest)(nil),  // 3: bilinotify.ai.v1.TestProviderRequest
	(*TestProviderResponse)(nil), // 4: bilinotify.ai.v1.TestProviderResponse
	(*TranscribeRequest)(nil),    // 5: bilinotify.ai.v1.TranscribeRequest
	(*SummaryRequest)(nil),       // 6: bilinotify.ai.v1.SummaryRequest
	(*Progress)(nil),             // 7: bilinotify.ai.v1.Progress
	(*TranscriptSegment)(nil),    // 8: bilinotify.ai.v1.TranscriptSegment
	(*TranscriptPage)(nil),       // 9: bilinotify.ai.v1.TranscriptPage
	(*TranscriptionResult)(nil),  // 10: bilinotify.ai.v1.TranscriptionResult
	(*SummaryResult)(nil),        // 11: bilinotify.ai.v1.SummaryResult
	(*Warning)(nil),              // 12: bilinotify.ai.v1.Warning
	(*WorkerEvent)(nil),          // 13: bilinotify.ai.v1.WorkerEvent
	nil,                          // 14: bilinotify.ai.v1.TranscribeRequest.CookiesEntry
	(*structpb.Struct)(nil),      // 15: google.protobuf.Struct
}
var file_ai_v1_worker_proto_depIdxs = []int32{
	2,  // 0: bilinotify.ai.v1.TestProviderRequest.provider:type_name -> bilinotify.ai.v1.ProviderConfig
	14, // 1: bilinotify.ai.v1.TranscribeRequest.cookies:type_name -> bilinotify.ai.v1.TranscribeRequest.CookiesEntry
	2,  // 2: bilinotify.ai.v1.TranscribeRequest.provider:type_name -> bilinotify.ai.v1.ProviderConfig
	2,  // 3: bilinotify.ai.v1.SummaryRequest.provider:type_name -> bilinotify.ai.v1.ProviderConfig
	8,  // 4: bilinotify.ai.v1.TranscriptPage.segments:type_name -> bilinotify.ai.v1.TranscriptSegment
	9,  // 5: bilinotify.ai.v1.TranscriptionResult.pages:type_name -> bilinotify.ai.v1.TranscriptPage
	15, // 6: bilinotify.ai.v1.TranscriptionResult.usage:type_name -> google.protobuf.Struct
	15, // 7: bilinotify.ai.v1.SummaryResult.usage:type_name -> google.protobuf.Struct
	7,  // 8: bilinotify.ai.v1.WorkerEvent.progress:type_name -> bilinotify.ai.v1.Progress
	10, // 9: bilinotify.ai.v1.WorkerEvent.transcription:type_name -> bilinotify.ai.v1.TranscriptionResult
	11, // 10: bilinotify.ai.v1.WorkerEvent.summary:type_name -> bilinotify.ai.v1.SummaryResult
	12, // 11: bilinotify.ai.v1.WorkerEvent.warning:type_name -> bilinotify.ai.v1.Warning
	0,  // 12: bilinotify.ai.v1.AIWorker.GetCapabilities:input_type -> bilinotify.ai.v1.CapabilitiesRequest
	3,  // 13: bilinotify.ai.v1.AIWorker.TestProvider:input_type -> bilinotify.ai.v1.TestProviderRequest
	5,  // 14: bilinotify.ai.v1.AIWorker.Transcribe:input_type -> bilinotify.ai.v1.TranscribeRequest
	6,  // 15: bilinotify.ai.v1.AIWorker.Summarize:input_type -> bilinotify.ai.v1.SummaryRequest
	1,  // 16: bilinotify.ai.v1.AIWorker.GetCapabilities:output_type -> bilinotify.ai.v1.CapabilitiesResponse
	4,  // 17: bilinotify.ai.v1.AIWorker.TestProvider:output_type -> bilinotify.ai.v1.TestProviderResponse
	13, // 18: bilinotify.ai.v1.AIWorker.Transcribe:output_type -> bilinotify.ai.v1.WorkerEvent
	13, // 19: bilinotify.ai.v1.AIWorker.Summarize:output_type -> bilinotify.ai.v1.WorkerEvent
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ai_v1_worker_proto_init() }
func file_ai_v1_worker_proto_init() {
	if File_ai_v1_worker_proto != nil {
		return
	}
	file_ai_v1_worker_proto_msgTypes[13].OneofWrappers = []any{
		(*WorkerEvent_Progress)(nil),
		(*WorkerEvent_Transcription)(nil),
		(*WorkerEvent_Summary)(nil),
		(*WorkerEvent_Warning)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_v1_worker_proto_rawDesc), len(file_ai_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_v1_worker_proto_goTypes,
		DependencyIndexes: file_ai_v1_worker_proto_depIdxs,
		MessageInfos:      file_ai_v1_worker_proto_msgTypes,
	}.Build()
	File_ai_v1_worker_proto = out.File
	file_ai_v1_worker_proto_goTypes = nil
	file_ai_v1_worker_proto_depIdxs = nil
}
